const VideoList = [
{
    "id": 1,
    "image_source" : require('./Assets/test.jpg'),
    "video_name" : "PS4 UnBoxing!!!",
    "channel_name" : "gaming_channel",
    "viewer_count" : "1.5M views",
}, 
{
    "id": 2,
    "image_source": require('./Assets/test2.jpg'),
    "video_name" : "ALMOST DIED ON HIKING TRIP!!!",
    "channel_name" : "HikingWarz",
    "viewer_count" : "2.5M views",
},
{
    "id": 3,
    "image_source" : require('./Assets/attraction1.jpg'),
    "video_name" : 'Top Attractions for 2017',
    "channel_name" : "wowSoFun",
    "viewer_count" : "500K views",
},

{
    "id": 4,
    "image_source": require('./Assets/planet2.jpg'),
    "video_name" : 'Unknown Planets',
    "channel_name" : "NACA",
    "viewer_count" : "1M views",
},
{
    "id": 5,
    "image_source": require('./Assets/ship2.jpg'),
    "video_name" : "NASA: Plans for 2018",
    "channel_name": "NationalSpaceChannel",
    "viewer_count" : "1.1B views",
},
{
    "id": 6,
    "image_source":  require('./Assets/ground1.png'),
    "video_name" : "How to Plant Crops on Dead Soil",
    "channel_name" : "ModernScience",
    "viewer_count" : "1.1M views",
},
{
    "id": 7,
    "image_source":  require('./Assets/grass2.png'),
    "video_name" : "Creating Cool 2D Grass Texture",
    "channel_name" : "QuickGraphics101",
    "viewer_count" : "300K views",
},
{
    "id": 8,
    "image_source":  require('./Assets/test3.png'),
    "video_name" : "Amazing Box Art in just 10 minutes!!",
    "channel_name" : "ArtistryRepulic",
    "viewer_count" : "180M views",
},
{
    "id": 9,
    "image_source":  require('./Assets/tower1.png'),
    "video_name" : " Ray's Tower Defense",
    "channel_name" : "Ripoff Studios",
    "viewer_count" : "900K views",   
},
{
    "id": 10,
    "image_source":  require('./Assets/samsung1.jpeg'),
    "video_name" : "Samsung Galaxy 8 REVIEW",
    "channel_name" : "DatReviewGuy",
    "viewer_count" : "9M views",   
},
{
    "id": 11,
    "image_source":  require('./Assets/bbq1.jpeg'),
    "video_name" : "BBQ Summer Tips",
    "channel_name" : "GrillBob",
    "viewer_count" : "400K views",   
},
{
    "id": 12,
    "image_source":  require('./Assets/stress1.jpeg'),
    "video_name" : "How To Deal With Stress",
    "channel_name" : "Cody1213",
    "viewer_count" : "340K views",   
},
{
    "id": 13,
    "image_source":  require('./Assets/pumpkin1.jpeg'),
    "video_name" : "Cook-Along: Pumpkin Soup",
    "channel_name" : "GreenCooks",
    "viewer_count" : "120K views",   
},
{
    "id": 14,
    "image_source":  require('./Assets/money1.png'),
    "video_name" : "Documentary- Hope For a Secure Future",
    "channel_name" : "RCDocumentary",
    "viewer_count" : "920K views",   
},
{
    "id": 15,
    "image_source":  require('./Assets/mario1.jpeg'),
    "video_name" : "News: New Mario Game Stucks Gold",
    "channel_name" : "GtGameNews",
    "viewer_count" : "400K views",   
},
{
    "id": 16,
    "image_source":  require('./Assets/baseball1.jpeg'),
    "video_name" : "Dodgers vs Atros Game 1 Highlights",
    "channel_name" : "MLpros",
    "viewer_count" : "200K views",   
},

]
export default VideoList